{
 "title": "Zimbra Dashboard",
 "description": "Zimbra Prometheus Exporter + Grafana Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ZCS Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zimbra_version{}", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Account",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zimbra_account_status_total{})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Days" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zimbra_uptime" }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zimbra_cpu_usage" }
   ]
  },
  {
   "title": "MEM",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zimbra_mem_usage" }
   ]
  },
  {
   "title": "DISK",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zimbra_disk_usage" }
   ]
  },
  {
   "title": "IO Wait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zimbra_iowait" }
   ]
  },
  { "title": "Service & Port", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zimbra_service_status ", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Port Listen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zimbra_port", "legendFormat": "{{name}}" }
   ]
  },
  { "title": "Transfer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_queue{name=\"active\"}"
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_queue{name=\"incoming\"}"
    }
   ]
  },
  {
   "title": "Hold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_queue{name=\"hold\"}"
    }
   ]
  },
  {
   "title": "Corrupt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_queue{name=\"corrupt\"}"
    }
   ]
  },
  {
   "title": "Deferred",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_queue{name=\"deferred\"}"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 10 },
   "targets": [
    { "expr": "zimbra_queue{}", "legendFormat": "{{name}}" }
   ]
  },
  { "title": "Account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_account_status_total{name=\"active\"}"
    }
   ]
  },
  {
   "title": "Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_account_status_total{name=\"active\"}"
    }
   ]
  },
  {
   "title": "Closed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_account_status_total{name=\"closed\"}"
    }
   ]
  },
  {
   "title": "Maintenance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_account_status_total{name=\"maintenance\"}"
    }
   ]
  },
  {
   "title": "Admin",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_account_status_total{name=\"closed\"}"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "zimbra_quota_usage", "legendFormat": "{{name}}" }
   ]
  },
  { "title": "Stats (Everyday 06:25~)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Bytes Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_stats{name=\"bytes_received\"}"
    }
   ]
  },
  {
   "title": "Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_stats{name=\"received\"}"
    }
   ]
  },
  {
   "title": "Senders",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_stats{name=\"senders\"}"
    }
   ]
  },
  {
   "title": "Deferred",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_stats{name=\"deferred\"}"
    }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_stats{name=\"rejected\"}"
    }
   ]
  },
  {
   "title": "Held",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_stats{name=\"held\"}"
    }
   ]
  },
  {
   "title": "Discarded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_stats{name=\"discarded\"}"
    }
   ]
  },
  {
   "title": "Bounced",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_stats{name=\"bounced\"}"
    }
   ]
  },
  {
   "title": "Bytes Delivered",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_stats{name=\"bytes_delivered\"}"
    }
   ]
  },
  {
   "title": "Delivered",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_stats{name=\"delivered\"}"
    }
   ]
  },
  {
   "title": "Recipients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_stats{name=\"recipients\"}"
    }
   ]
  },
  {
   "title": "Forwarded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_stats{name=\"forwarded\"}"
    }
   ]
  },
  {
   "title": "Reject Warnings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zimbra_stats{name=\"reject_warnings\"}"
    }
   ]
  }
 ]
}