{
 "title": "UniFi AP Dashboard",
 "description": "Ubiquiti Networks UniFi AP Dashboard",
 "tags": [
  "AP",
  "System",
  "Templated",
  "UBNT",
  "UniFi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "UniFi AP:",
    "query": "SHOW TAG VALUES FROM \"snmp.UAP\" WITH KEY = \"agent_host\""
   },
   {
    "name": "radio",
    "label": "Radio",
    "query": "SHOW TAG VALUES FROM \"unifiVapTable\" WITH KEY = \"unifiVapRadio\" WHERE \"agent_host\" =~ /^$host$/"
   },
   {
    "name": "vap",
    "label": "vAP:",
    "query": "SHOW TAG VALUES FROM \"unifiVapTable\" WITH KEY = \"unifiVapName\" WHERE \"agent_host\" =~ /^$host$/"
   },
   {
    "name": "intf",
    "label": "Interface:",
    "query": "SHOW TAG VALUES FROM \"unifiIfTable\" WITH KEY = \"unifiIfName\" WHERE \"agent_host\" =~ /^$host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "$host",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "sysName" ], "type": "tag" }
     ],
     "measurement": "snmp.UAP",
     "select": [
      [
       { "params": [ "unifiApSystemModel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiApSystemVersion" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Version" ], "type": "alias" }
      ],
      [
       { "params": [ "sysDescr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Description" ], "type": "alias" }
      ],
      [
       { "params": [ "sysContact" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Contact" ], "type": "alias" }
      ],
      [
       { "params": [ "sysLocation" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Location" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "snmp.UAP",
     "select": [
      [
       { "params": [ "sysUpTime" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Radios",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "alias": "$tag_unifiVapRadio",
     "groupBy": [
      { "params": [ "unifiVapRadio" ], "type": "tag" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapChannel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Channel" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapExtChannel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Ext" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapTxPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Tx Power" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=~", "value": "/^$vap$/" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=~", "value": "/^$radio$/" }
     ]
    }
   ]
  },
  {
   "title": "RF Channel Utilization",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_unifiRadioRadio",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "unifiRadioRadio" ], "type": "tag" }
     ],
     "measurement": "unifiRadioTable",
     "select": [
      [
       { "params": [ "unifiRadioCuTotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "unifiRadioRadio", "operator": "=~", "value": "/^$radio$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "options": {
    "content": "<p style=\"text-align:center; vertical-align: middle;\"><img src=\"https://dl.ubnt.com/press/logo-UniFi.png\" height=\"50\"  alt=\"UniFi\"/></p>"
   }
  },
  {
   "title": "CPU Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_laNames Minute",
     "groupBy": [
      { "params": [ "laNames" ], "type": "tag" }
     ],
     "measurement": "laTable",
     "select": [
      [
       { "params": [ "laLoadInt" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Processor Load (1 Minute Average)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_index",
     "groupBy": [
      { "params": [ "index" ], "type": "tag" }
     ],
     "measurement": "hrProcessorTable",
     "select": [
      [
       { "params": [ "hrProcessorLoad" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "snmp.UAP",
     "select": [
      [
       { "params": [ "memBuffer" ], "type": "field" },
       { "params": [ "Buffer" ], "type": "alias" }
      ],
      [
       { "params": [ "memCached" ], "type": "field" },
       { "params": [ "Cache" ], "type": "alias" }
      ],
      [
       { "params": [ "memShared" ], "type": "field" },
       { "params": [ "Shared" ], "type": "alias" }
      ],
      [
       { "params": [ "memTotalFree" ], "type": "field" },
       { "params": [ "Free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.UAP",
     "query": "SELECT ((\"memTotalReal\"-\"memAvailReal\")/\"memTotalReal\") AS \"Real\" FROM \"snmp.UAP\" WHERE (\"agent_host\" =~ /^$host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "memAvailReal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Real" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Stations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_unifiVapName: $tag_unifiVapEssId ($tag_unifiVapRadio)",
     "groupBy": [
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "unifiVapRadio" ], "type": "tag" },
      { "params": [ "unifiVapEssId" ], "type": "tag" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapNumStations" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=~", "value": "/^$vap$/" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=~", "value": "/^$radio$/" }
     ]
    }
   ]
  },
  {
   "title": "Other BSS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_unifiRadioRadio ($tag_unifiRadioName)",
     "groupBy": [
      { "params": [ "unifiRadioName" ], "type": "tag" },
      { "params": [ "unifiRadioRadio" ], "type": "tag" }
     ],
     "measurement": "unifiRadioTable",
     "select": [
      [
       { "params": [ "unifiRadioOtherBss" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "unifiRadioRadio", "operator": "=~", "value": "/^$radio$/" }
     ]
    }
   ]
  },
  {
   "title": "WiFi (802.11) Channel Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_unifiRadioRadio:  $col",
     "groupBy": [
      { "params": [ "unifiRadioRadio" ], "type": "tag" }
     ],
     "measurement": "unifiRadioTable",
     "select": [
      [
       { "params": [ "unifiRadioCuSelfRx" ], "type": "field" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiRadioCuSelfTx" ], "type": "field" },
       { "params": [ "Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiRadioCuTotal" ], "type": "field" },
       { "params": [ "Busy" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "unifiRadioRadio", "operator": "=~", "value": "/^$radio$/" }
     ]
    }
   ]
  },
  {
   "title": "WiFi (802.11) Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$tag_unifiVapName:  $col",
     "groupBy": [
      { "params": [ "unifiVapName" ], "type": "tag" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapRxBytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapTxBytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=~", "value": "/^$vap$/" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=~", "value": "/^$radio$/" }
     ]
    }
   ]
  },
  {
   "title": "WiFi (802.11) Traffic Distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_unifiVapName:  $col",
     "groupBy": [
      { "params": [ "unifiVapName" ], "type": "tag" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapRxPackets" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapTxPackets" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=~", "value": "/^$vap$/" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=~", "value": "/^$radio$/" }
     ]
    }
   ]
  },
  {
   "title": "WiFi (802.11) Drops/Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_unifiVapName:  $col",
     "groupBy": [
      { "params": [ "unifiVapName" ], "type": "tag" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapRxDropped" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Drop:  In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapTxDropped" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Drop:  Out" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapRxErrors" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:  In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapTxErrors" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:  Out" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapRxCrypts" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "BadCrypt:  In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapRxFrags" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "BadFrag:  In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapTxRetries" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "ExsRetry:  Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=~", "value": "/^$vap$/" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=~", "value": "/^$radio$/" }
     ]
    }
   ]
  },
  {
   "title": "Ethernet (802.3) Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$tag_unifiIfName:  $col",
     "groupBy": [
      { "params": [ "unifiIfName" ], "type": "tag" }
     ],
     "measurement": "unifiIfTable",
     "select": [
      [
       { "params": [ "unifiIfRxBytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiIfTxBytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "unifiIfName", "operator": "=~", "value": "/^$intf$/" }
     ]
    }
   ]
  },
  {
   "title": "Ethernet (802.3) Traffic Distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_unifiIfName:  $col",
     "groupBy": [
      { "params": [ "unifiIfName" ], "type": "tag" }
     ],
     "measurement": "unifiIfTable",
     "select": [
      [
       { "params": [ "unifiIfRxPackets" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Ucast:  In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiIfTxPackets" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Ucast:  Out" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiIfRxMulticast" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Mcast:  In" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "unifiIfName", "operator": "=~", "value": "/^$intf$/" }
     ]
    }
   ]
  },
  {
   "title": "Ethernet (802.3) Drops/Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_unifiIfName:  $col",
     "groupBy": [
      { "params": [ "unifiIfName" ], "type": "tag" }
     ],
     "measurement": "unifiIfTable",
     "select": [
      [
       { "params": [ "unifiIfRxDropped" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Drop:  In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiIfTxDropped" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Drop:  Out" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiIfRxError" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:  In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiIfTxError" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:  Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "unifiIfName", "operator": "=~", "value": "/^$intf$/" }
     ]
    }
   ]
  },
  {
   "title": "All Interface Drops/Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_ifDescr:  $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifDescr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifTable",
     "query": "SELECT non_negative_derivative(mean(\"ifInDiscards\"), 1s) AS \"Drop:  In\", non_negative_derivative(mean(\"ifOutDiscards\"), 1s) AS \"Drop:  Out\", non_negative_derivative(mean(\"ifInErrors\"), 1s) AS \"Error:  In\", non_negative_derivative(mean(\"ifOutErrors\"), 1s) AS \"Error:  Out\", non_negative_derivative(mean(\"ifInUnknownProtos\"), 1s) AS \"Unkwn:  In\" FROM \"ifTable\" WHERE \"agent_host\" =~ /^$host$/ AND \"ifOperStatus\" = 1 AND $timeFilter GROUP BY time($__interval), \"ifDescr\" fill(null)",
     "select": [
      [
       { "params": [ "ifInDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Drop:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOutDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Drop:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ifInErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOutErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ifInUnknownProtos" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Unkwn:In" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ifOperStatus", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "SNMP Messages (/min)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "snmp.UAP",
     "select": [
      [
       { "params": [ "snmpInPkts" ], "type": "field" },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "Msgs:  In" ], "type": "alias" }
      ],
      [
       { "params": [ "snmpOutPkts" ], "type": "field" },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "Msgs:  Out" ], "type": "alias" }
      ],
      [
       { "params": [ "snmpInGetResponses" ], "type": "field" },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "GetResp:  In" ], "type": "alias" }
      ],
      [
       { "params": [ "snmpOutGetResponses" ], "type": "field" },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "GetResp:  Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"allReqIn\"), 1m) AS \"GetReq:  In\", non_negative_derivative(mean(\"allReqOut\"), 1m) AS \"GetReq:  Out\" FROM ( SELECT \"snmpInGetRequests\"+\"snmpInGetNexts\" AS \"allReqIn\", \"snmpOutGetRequests\"+\"snmpOutGetNexts\" AS \"allReqOut\" FROM \"snmp.UAP\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter) WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SNMP Objects Retrieved (/min)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "snmp.UAP",
     "select": [
      [
       { "params": [ "snmpInTotalReqVars" ], "type": "field" },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "Objects" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}